- name: Provisioning Servers
  hosts: all
  become: yes
  tasks:
    - name: Install ntp agent on ubuntu
      apt:
        name: ntp
        state: present
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

    - name: Start ntp service on ubuntu
      service:
        name: ntp
        state: started
        enabled: yes
      when: ansible_distribution == "Ubuntu"
        
    - name: Install ntp agent on centos
      yum:
        name: chrony
        state: present
      when: ansible_distribution == "CentOS"

    - name: Start ntp service on centos
      service: 
        name: chrony
        state: started
        enabled: yes
      when: ansible_distribution == "CentOS"

